### ISSUE TITLE
Build Issues

### ISSUE THREAD

**Issue by Yh010** [siinghd/question-tracker#24]
.env.vault doesn't contain the encrypted secrets. SInce there are no secrets, I am facing build issues(Environment variables not found).

`
`> simple-app@0.1.1 dev
> next dev

   ▲ Next.js 14.0.4
   - Local:        http://localhost:3000

/bin/sh: 1: pnpm: not found
 ✓ Ready in 4.3s
 ○ Compiling /middleware ...
 ✓ Compiled /middleware in 1897ms (207 modules)
[auth][error] MissingSecret: Please define a `secret`. .Read more at https://errors.authjs.dev#missingsecret
    at assertConfig (webpack-internal:///(middleware)/./node_modules/next-auth/node_modules/@auth/core/lib/utils/assert.js:49:16)
    at Auth (webpack-internal:///(middleware)/./node_modules/next-auth/node_modules/@auth/core/index.js:82:95)
 ○ Compiling / ...
(node:10103) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
 ✓ Compiled / in 15.4s (2608 modules)
[auth][error] MissingSecret: Please define a `secret`. .Read more at https://errors.authjs.dev#missingsecret
    at assertConfig (webpack-internal:///(rsc)/./node_modules/next-auth/node_modules/@auth/core/lib/utils/assert.js:49:16)
    at Auth (webpack-internal:///(rsc)/./node_modules/next-auth/node_modules/@auth/core/index.js:82:95)
[auth][error] MissingSecret: Please define a `secret`. .Read more at https://errors.authjs.dev#missingsecret
    at assertConfig (webpack-internal:///(rsc)/./node_modules/next-auth/node_modules/@auth/core/lib/utils/assert.js:49:16)
    at Auth (webpack-internal:///(rsc)/./node_modules/next-auth/node_modules/@auth/core/index.js:82:95)
{
  message: 'There was a problem with the server configuration. Check the server logs for more information.',
  code: 'MissingSecret'
}
 ⨯ PrismaClientInitializationError: 
Invalid `prisma.question.findMany()` invocation:

error: Environment variable not found: DATABASE_URL.
  -->  schema.prisma:10
   | 
 9 |   provider = "mongodb"
10 |   url      = env("DATABASE_URL")
   | 

Validation Error Count: 1
    at async Home (./app/page.tsx:32:16)
 ⨯ PrismaClientInitializationError: 
Invalid `prisma.question.findMany()` invocation:

error: Environment variable not found: DATABASE_URL.
  -->  schema.prisma:10
   | 
 9 |   provider = "mongodb"
10 |   url      = env("DATABASE_URL")
   | 

Validation Error Count: 1
    at async Home (./app/page.tsx:32:16)
digest: "4291745356"
 ✓ Compiled in 1502ms (1051 modules)
[auth][error] MissingSecret: Please define a `secret`. .Read more at https://errors.authjs.dev#missingsecret
    at assertConfig (webpack-internal:///(middleware)/./node_modules/next-auth/node_modules/@auth/core/lib/utils/assert.js:49:16)
    at Auth (webpack-internal:///(middleware)/./node_modules/next-auth/node_modules/@auth/core/index.js:82:95)
 ○ Compiling /favicon.ico ...
 ✓ Compiled /favicon.ico in 3.6s (2535 modules)
[auth][error] MissingSecret: Please define a `secret`. .Read more at https://errors.authjs.dev#missingsecret
    at assertConfig (webpack-internal:///(middleware)/./node_modules/next-auth/node_modules/@auth/core/lib/utils/assert.js:49:16)
    at Auth (webpack-internal:///(middleware)/./node_modules/next-auth/node_modules/@auth/core/index.js:82:95)
[auth][error] MissingSecret: Please define a `secret`. .Read more at https://errors.authjs.dev#missingsecret
    at assertConfig (webpack-internal:///(middleware)/./node_modules/next-auth/node_modules/@auth/core/lib/utils/assert.js:49:16)
    at Auth (webpack-internal:///(middleware)/./node_modules/next-auth/node_modules/@auth/core/index.js:82:95)
[auth][error] MissingSecret: Please define a `secret`. .Read more at https://errors.authjs.dev#missingsecret
    at assertConfig (webpack-internal:///(rsc)/./node_modules/next-auth/node_modules/@auth/core/lib/utils/assert.js:49:16)
    at Auth (webpack-internal:///(rsc)/./node_modules/next-auth/node_modules/@auth/core/index.js:82:95)
[auth][error] MissingSecret: Please define a `secret`. .Read more at https://errors.authjs.dev#missingsecret
    at assertConfig (webpack-internal:///(rsc)/./node_modules/next-auth/node_modules/@auth/core/lib/utils/assert.js:49:16)
    at Auth (webpack-internal:///(rsc)/./node_modules/next-auth/node_modules/@auth/core/index.js:82:95)
{
  message: 'There was a problem with the server configuration. Check the server logs for more information.',
  code: 'MissingSecret'
}
 ⨯ PrismaClientInitializationError: 
Invalid `prisma.question.findMany()` invocation:

error: Environment variable not found: DATABASE_URL.
  -->  schema.prisma:10
   | 
 9 |   provider = "mongodb"
10 |   url      = env("DATABASE_URL")
   | 

Validation Error Count: 1
    at async Home (./app/page.tsx:32:16)
 ⨯ PrismaClientInitializationError: 
Invalid `prisma.question.findMany()` invocation:

error: Environment variable not found: DATABASE_URL.
  -->  schema.prisma:10
   | 
 9 |   provider = "mongodb"
10 |   url      = env("DATABASE_URL")
   | 

Validation Error Count: 1
    at async Home (./app/page.tsx:32:16)
digest: "4291745356"
[auth][error] MissingSecret: Please define a `secret`. .Read more at https://errors.authjs.dev#missingsecret
    at assertConfig (webpack-internal:///(middleware)/./node_modules/next-auth/node_modules/@auth/core/lib/utils/assert.js:49:16)
    at Auth (webpack-internal:///(middleware)/./node_modules/next-auth/node_modules/@auth/core/index.js:82:95)
[auth][error] MissingSecret: Please define a `secret`. .Read more at https://errors.authjs.dev#missingsecret
    at assertConfig (webpack-internal:///(middleware)/./node_modules/next-auth/node_modules/@auth/core/lib/utils/assert.js:49:16)
    at Auth (webpack-internal:///(middleware)/./node_modules/next-auth/node_modules/@auth/core/index.js:82:95)
[auth][error] MissingSecret: Please define a `secret`. .Read more at https://errors.authjs.dev#missingsecret
    at assertConfig (webpack-internal:///(middleware)/./node_modules/next-auth/node_modules/@auth/core/lib/utils/assert.js:49:16)
    at Auth (webpack-internal:///(middleware)/./node_modules/next-auth/node_modules/@auth/core/index.js:82:95)
^C
`
`

**Comment by siinghd** [comment]
@Yh010 The .env file is missing i will try to default  .env with default credentials
